#!/usr/bin/env python3
"""Regenerate dialects/mysql_casefold_table.go — the MySQL identifier case-fold table, as Go code.

Source of truth: MySQL's `my_unicase_default` `.tolower` map (the case map used by
`utf8mb3_general_ci`, which is `system_charset_info` — the collation MySQL resolves
identifiers under). It is a simple 1:1, accent-PRESERVING, BMP-only lowercase:
    É -> é   (0x00C9 -> 0x00E9)   but   Ñ != N   and   ß unchanged.

Neither Go's strings.ToLower nor the JVM's String.lowercase() reproduces this map, and they
diverge from each other on characters like U+0130 / final sigma. The table is baked into Go code
here so the fold is a single implementation with no runtime data file; a JVM/other consumer should
reproduce the fold by calling the exported dialects.MySQLLower via a native binding (one impl, no
drift), or by regenerating this same table.

Usage:
    # 1. get the pinned MySQL source (branch 8.0):
    #    curl -sL https://raw.githubusercontent.com/mysql/mysql-server/8.0/strings/ctype-utf8.cc -o /tmp/ctype-utf8.cc
    # 2. regenerate, then `gofmt -w`:
    python3 scripts/gen_mysql_casefold.py /tmp/ctype-utf8.cc dialects/mysql_casefold_table.go

Verified anchors (mysql-server @ 8.0): the identifier collation
`my_charset_utf8mb3_general_ci` uses `caseinfo = &my_unicase_default`; that table's page map
`my_unicase_pages_default[256]` selects the per-page `MY_UNICASE_CHARACTER planeXX[]` tables,
each entry `{toupper, .tolower, sort}` — identifier folding reads `.tolower` (NOT `.sort`,
which is the accent-folding collation weight).
"""
import re
import sys

TERM = r"\}\s*;"  # array close "};"; inner triples "{a,b,c}," never contain it


def parse_plane(src: str, name: str) -> list[int]:
    m = re.search(r"MY_UNICASE_CHARACTER " + re.escape(name) + r"\[\]\s*=\s*\{(.*?)" + TERM, src, re.S)
    if not m:
        raise SystemExit(f"plane not found: {name}")
    triples = re.findall(r"\{\s*0x([0-9A-Fa-f]+)\s*,\s*0x([0-9A-Fa-f]+)\s*,\s*0x([0-9A-Fa-f]+)\s*\}", m.group(1))
    if len(triples) != 256:
        raise SystemExit(f"{name}: expected 256 entries, got {len(triples)}")
    return [int(t[1], 16) for t in triples]  # .tolower (2nd field)


def main() -> None:
    if len(sys.argv) != 3:
        raise SystemExit("usage: gen_mysql_casefold.py <ctype-utf8.cc> <out.tsv>")
    src = open(sys.argv[1]).read()

    pm = re.search(r"my_unicase_pages_default\[256\]\s*=\s*\{(.*?)" + TERM, src, re.S).group(1)
    tokens = [t.strip() for t in pm.split(",") if t.strip()]
    if len(tokens) != 256:
        raise SystemExit(f"page map: expected 256, got {len(tokens)}")

    planes: dict[str, list[int]] = {}
    mapping: dict[int, int] = {}
    for page, tok in enumerate(tokens):
        if tok in ("nullptr", "NULL", "0"):
            continue
        if tok not in planes:
            planes[tok] = parse_plane(src, tok)
        low = planes[tok]
        base = page << 8
        for off in range(256):
            cp, lo = base + off, low[off]
            if lo != cp and lo != 0:
                mapping[cp] = lo

    keys = sorted(mapping)
    with open(sys.argv[2], "w") as f:
        f.write("// Code generated by scripts/gen_mysql_casefold.py; DO NOT EDIT.\n//\n")
        f.write("// MySQL identifier case-fold table — byte-exact, from MySQL 8.0 my_unicase_default\n")
        f.write("// `.tolower` (utf8mb3_general_ci = system_charset_info), strings/ctype-utf8.cc. Simple 1:1\n")
        f.write("// lowercase, accent-PRESERVING, BMP-only (utf8mb3): É->é but Ñ!=N, ß unchanged. Only code\n")
        f.write("// points whose fold differs from identity are listed. See dialects/mysql_casefold.go +\n")
        f.write("// DEVIATIONS.md §1.2. Neither strings.ToLower nor the JVM's lowercase() reproduces this map.\n\n")
        f.write("package dialects\n\n")
        f.write(f"// mysqlLowerMap maps a code point to its MySQL lowercase ({len(keys)} BMP entries).\n")
        f.write("var mysqlLowerMap = map[rune]rune{\n")
        for i in range(0, len(keys), 6):
            row = "".join(f"0x{cp:04X}: 0x{mapping[cp]:04X}, " for cp in keys[i:i + 6])
            f.write("\t" + row.rstrip() + "\n")
        f.write("}\n")
    print(f"wrote {sys.argv[2]} ({len(mapping)} entries; planes {sorted(planes)})")


if __name__ == "__main__":
    main()
